import { CELL_SIZE, DELTA_TIME, GAP_SIZE, GRID_HEIGHT, GRID_WIDTH } from '../../shared/constants';

export { CELL_SIZE, DELTA_TIME, GAP_SIZE, GRID_HEIGHT, GRID_WIDTH };

export const MINESWEEPER_HEADER_HEIGHT = 24;
export const MINESWEEPER_CELL_RADIUS = 3;
export const MINESWEEPER_MIN_DURATION_MS = 5000;
export const MINESWEEPER_DURATION_DIVISOR = 1.2;
export const MINESWEEPER_MAX_STEPS = GRID_WIDTH * GRID_HEIGHT * 3;
export const MINESWEEPER_END_HOLD_FRAMES = 12;
export const MINESWEEPER_MAX_MOVE_DURATION_MS = 1000;
export const MINESWEEPER_MS_PER_FRAME = DELTA_TIME / MINESWEEPER_DURATION_DIVISOR;
export const MINESWEEPER_MAX_MOVE_FRAMES = Math.max(1, Math.ceil(MINESWEEPER_MAX_MOVE_DURATION_MS / MINESWEEPER_MS_PER_FRAME));
